[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "AirTrack"
authors = [{name = "Felix Slama", email = "fs@fslama.com"}]
dynamic = ["version", "description"]
